collide: Expose CollisionPolygon's setup_points and verify_points to Python
panda3d/panda3d pull request #1035
Opened 2020-10-13 21:21 UTC by darktohka

## Issue description
I would like to set a CollisionPolygon's list of points. Unfortunately, the sequence wrapper over `_points` does not allow this to happen. Fortunately, CollisionPolygon has a `setup_points` method, but this method's visibility is set to private.

## Solution description
This PR set's `setup_points` visibility to public, and adds a Python wrapper for both `setup_points` and `verify_points`, to allow these functions to be called from Python code.

## Checklist
I have done my best to ensure that…
* [X] …I have familiarized myself with the CONTRIBUTING.md file
* [X] …this change follows the coding style and design patterns of the codebase
* [X] …I own the intellectual property rights to this code
* [X] …the intent of this change is clearly explained
* [X] …existing uses of the Panda3D API are not broken
* [ ] …the changed code is adequately covered by the test suite, where possible.

2020-10-21 22:27 UTC, rdb requested changes
Looks good, except this won't work in double-precision mode as-is because your code uses LPoint3f whereas the function takes LPoint3.

You may need to disambiguate between Dtool_LPoint3f and Dtool_LPoint3d based on STDFLOAT_DOUBLE since there is no Dtool_LPoint3.

It should not be hard to add unit tests for this.

2020-10-21 22:28 UTC, rdb commented on panda/src/collide/collisionPolygon_ext.h
> +    void setup_points(PyObject *points);
Too much indent

2020-11-22 13:25 UTC, darktohka commented
The requested changes have been made. Unit tests have been added for both methods, the distinction between Point3d and Point3f is now made, and verify_points is now static.

2020-11-22 16:43 UTC, rdb approved these changes
LGTM

2020-11-22 21:01 UTC, closed without merging