create PY_EXTENSION and friends
panda3d/panda3d pull request #1415
Opened 2023-01-02 21:23 UTC by Frangwhuf

## Issue description
Reduce some `ifdef` chaff and make the scripting target for a Python extension clearer. See [Issue #1414](https://github.com/panda3d/panda3d/issues/1414)

## Solution description
Created `PY_EXTENSION`, `PY_EXTEND`, `PY_MAKE_PROPERTY`, and `PY_MAKE_SEQ_PROPERTY` (for these last two, they were the only ones currently needed). These mimic the behavior of the non-PY versions with the added condition that if HAVE_PYTHON is not defined, they drop the contents as would normally happen with CPPPARSER undefined. Further, the `PY_EXTEND` macro is expressed as variadic (unlike `EXTEND`) so that it can consume its contents properly. (It may be worth considering doing this with `EXTEND` as well.)

## Checklist
I have done my best to ensure that…
* [x] …I have familiarized myself with the CONTRIBUTING.md file
* [x] …this change follows the coding style and design patterns of the codebase
* [x] …I own the intellectual property rights to this code
* [x] …the intent of this change is clearly explained
* [x] …existing uses of the Panda3D API are not broken
* [x] …the changed code is adequately covered by the test suite, where possible.

2023-01-03 21:54 UTC, rdb requested changes
Great, much better.  Thank you!  Just a few cases where the alignment is off now.

It's not really a big deal here, but for future reference, I would prefer to put unrelated cleanup changes (such as `#endif` comments) in a separate commit, so that it's easier to sort out the important parts of a change in a diff - also easier to untangle things if a change ever needs to be reverted.

2023-01-03 21:54 UTC, rdb commented on panda/src/gobj/geomVertexArrayData.h
>                                     size_t from_start, size_t from_size));
Nitpick: alignment is wrong now

2023-01-03 21:54 UTC, rdb commented on panda/src/gobj/texture.h
> +                            size_t page_size = 0));
Alignment

2023-01-03 21:54 UTC, rdb commented on panda/src/ode/odeUtil.h
>                                  PyObject* arg, PyObject* callback));
Alignment

2023-01-04 15:01 UTC, Frangwhuf commented
Two questions:
 
- Is the preferred mechanism for resolving the above a separate commit on the PR, or to squash the changes together?
- For future janitorial updates (endif comments, etc) is the preferred approach to make that a separate PR or just a separate commit in the PR?

2023-01-04 19:16 UTC, rdb commented
It takes only a single click for a maintainer to squash the commits in a PR, so I'd say, whatever is easiest for you. :)

As for the (uncontroversial) janitorial updates, since you are a Panda dev I think you should just push them directly to the repo.  In the general case, a separate PR would be cleanest if the changes are unrelated, so that they can be reviewed and applied separately.  That said, I would consider a separate commit on the same PR also OK if the changes are interwoven such that dealing with the merge conflicts would just be a PITA.

2023-01-04 19:54 UTC, merged