prints() and parenthesis for exceptions
panda3d/panda3d pull request #1490
Opened 2023-04-22 08:20 UTC by BMaxV

## Issue description
I was running radon cc and that threw error messages. Turns out there were still some python 2 remnants in there.

## Solution description
```
print "text" -> print("text")

...
except e1, e2 : > except (e1,e2):
...
```
## Checklist
I have done my best to ensure that…
* [x] …I have familiarized myself with the CONTRIBUTING.md file
* [x] …this change follows the coding style and design patterns of the codebase
* [x] …I own the intellectual property rights to this code
* [x] …the intent of this change is clearly explained
* [x] …existing uses of the Panda3D API are not broken
* [ ] …the changed code is adequately covered by the test suite, where possible.

2023-05-02 12:25 UTC, rdb requested changes

2023-05-02 12:25 UTC, rdb commented on panda/src/iphone/ipfreeze.py
> +    print( sys.stderr, msg)
This is not the correct way to replace this syntax in Python 3, use `file=`

2023-05-02 12:25 UTC, rdb commented on panda/src/iphone/ipfreeze.py
> +    except (getopt.error, msg):
This is not equivalent, use `as`.

2023-05-02 12:25 UTC, rdb commented on panda/src/testbed/test_native_net2.py
> +print (addr.getIpPort())
No space before parenthesis in function calls

2023-05-02 12:40 UTC, rdb commented on panda/src/iphone/ipfreeze.py
> +    print(file=sys.stderr, msg)
```
>>> print(file=sys.stderr, "abc")
  File "<stdin>", line 1
SyntaxError: positional argument follows keyword argument
```

2023-05-03 15:38 UTC, rdb approved these changes

2023-05-07 13:41 UTC, closed without merging

2023-05-07 13:42 UTC, BMaxV commented
Changes were merged.