task: Annotate core functions
panda3d/panda3d pull request #1548
Opened 2023-10-11 18:07 UTC by WMOkiishi

## Change description
These changes add type annotations to the core functions in the `task` module (mostly `TaskManager` methods). Tests have been added for annotated functions that aren't used elsewhere in the codebase. Some additional cleanup had also been done to the existing tests for the `task` module.

## Checklist
I have done my best to ensure that…
* [x] …I have familiarized myself with the CONTRIBUTING.md file
* [x] …this change follows the coding style and design patterns of the codebase
* [x] …I own the intellectual property rights to this code
* [x] …the intent of this change is clearly explained
* [x] …existing uses of the Panda3D API are not broken
* [x] …the changed code is adequately covered by the test suite, where possible.

2023-10-11 21:01 UTC, rdb requested changes

2023-10-11 22:08 UTC, WMOkiishi commented on direct/src/task/Task.py
>              return self.mgr.remove(taskOrName)
`bool` is a subclass of `int` in Python (for historical reasons), so, technically, this is fine as-is. That being said, I wouldn't have an issue adding a conversion to an `int` here if you'd like.

2023-10-12 19:38 UTC, rdb commented on direct/src/task/Task.py
>              return self.mgr.remove(taskOrName)
Interesting.  Okay, for the purposes of the annotations it's fine then, though I want to make this change eventually for consistency.

2023-10-13 19:20 UTC, rdb approved these changes

2023-10-13 19:20 UTC, merged