Ability to read comments/metadata from sound files
panda3d/panda3d pull request #1656
Opened 2024-05-14 12:17 UTC by Wizzerinus

## Issue description
This PR allows loading metadata/comments/tags from sound files and exposes those to the programmer. Example code:

```python
from direct.showbase.ShowBase import ShowBase
from panda3d.core import loadPrcFileData

loadPrcFileData("", "audio-library-name p3openal_audio")
b = ShowBase()
f = b.loader.loadMusic("file.ogg")
print(list(f.raw_comments))  # something like ['ARTIST=artist', 'TITLE=my music track\n']
print(f.comments['TITLE'])  # something like 'my music traсk'
```

## Solution description
Metadata is exposed through two virtual methods, one on the AudioCursor, and another one on the AudioSound, linked through some binding code in AudioManager.

We have 3 sound managers, FMod, Null and OpenAL. FMod is way too encapsulated to do anything, and Null is Null, so those 2 managers return an empty string when the comment is read. For OpenAL, the method depends on the underlying AudioCursor class.

There are seven types of AudioCursor: FFmpeg, Opus, Flac, Wav, Vorbis, Microphone and Userdata. Only three of these currently have an implementation:
- Implementation for FFmpeg is based on https://ffmpeg.org/doxygen/0.7/metadata-example_8c-source.html. Note that FFmpeg uses a different data structure from ogg, which had to be converted to `vector<string>`.
- Implementation for Opus and Vorbis is more or less the same with minor differences based on how the Tag struct is accessed.
- There is no implementation for Flac. The reason being the Panda3D's dr_flac implementation being extremely old and that version does not have the metadata iterator. This can be revisited in the future when/if the bundled dr_flac is updated.
- Wav does not have an implementation seeing as Panda uses bytestring interaction to parse those files, and the standard does not seem to have a Metadata field. Therefore using `getComment()` returns an empty string here also.
- Microphone and Userdata don't have an implementation for an obvious reason.

~~Due to an interrogate limitation, the published C++ functions return `string` which is obtained by joining the vector of comments with newlines. Not sure if there's a better way.~~ no longer the case, see below

I've tested the implementation on Libvorbis which seems to work correctly, did not test FFmpeg and Opus (besides ensuring the engine compiles and can be imported without ABI errors) since there is no documentation on how to force Panda to use a specific cursor loader.

## Checklist
I have done my best to ensure that…
* [x] …I have familiarized myself with the CONTRIBUTING.md file
* [x] …this change follows the coding style and design patterns of the codebase
* [x] …I own the intellectual property rights to this code
* [x] …the intent of this change is clearly explained
* [x] …existing uses of the Panda3D API are not broken
* [x] …the changed code is adequately covered by the test suite, where possible.

2024-05-14 13:57 UTC, rdb commented
Great work, thank you!  Some comments.

We're trying to phase out Python extensions added in direct. They're only available when direct is loaded. Prefer a C++ interface if at all possible, or a C++-implemented extension method (see _ext.h and _ext.cxx files) if nothing else is possible.

Doing it in C++ would mean making sequential access methods (which means you could parse it into a SimpleHashMap, that supports both key-based and indexed access) and exposing those to Python with MAKE_MAP_PROPERTY - do a grep for that to search for examples.  We can keep the C++ methods making up the map-property as unpublished, so that the property is the only way to access it from Python.

An alternative is making an AudioTags class which exposes a mapping interface (overriding `operator []`), and so behaves like a dictionary.  Then we just need a getter property on the AudioSound.  This would be the preferred method if the interface is bigger (like an AudioMetadata containing more than just tags), so that the AudioSound interface isn't cluttered up.  If it's just a dict of tags, I think MAKE_MAP_PROPERTY might be easier.

I don't think that we should have this interface on both AudioSound and MovieAudioCursor.  Intuitively, MovieAudio should be the place for this, but it seems some implementations don't actually open the sound file until the cursor is created, so MovieAudioCursor sounds like the place to get it.  Is there a reason to also have it on AudioSound?

Would it be interesting to give thought to standardizing the keys between different formats, so that you can use the same code to access the title of an .mp3 file as for an .ogg file, via a named enum or named getters, or do you think the original keys should be kept?

Feel free to ping me on Discord for more discussion.

2024-05-14 18:55 UTC, Wizzerinus commented
> We're trying to phase out Python extensions added in direct. They're only available when direct is loaded. Prefer a C++ interface if at all possible, or a C++-implemented extension method (see _ext.h and _ext.cxx files) if nothing else is possible.
> Doing it in C++ would mean making sequential access methods (which means you could parse it into a SimpleHashMap, that supports both key-based and indexed access) and exposing those to Python with MAKE_MAP_PROPERTY - do a grep for that to search for examples. We can keep the C++ methods making up the map-property as unpublished, so that the property is the only way to access it from Python.

Implemented this. An interesting difference now is that you can no longer "parse all comments", only "comments with a given named tag". Not sure whether this is a significant issue or not. I could still expose the string as something like `getCommentString()` (since `getRawComment()` is now a vector).

> An alternative is making an AudioTags class which exposes a mapping interface (overriding operator []), and so behaves like a dictionary. Then we just need a getter property on the AudioSound. This would be the preferred method if the interface is bigger (like an AudioMetadata containing more than just tags), so that the AudioSound interface isn't cluttered up. If it's just a dict of tags, I think MAKE_MAP_PROPERTY might be easier.

Decided against it since it felt overkill.

> I don't think that we should have this interface on both AudioSound and MovieAudioCursor. Intuitively, MovieAudio should be the place for this, but it seems some implementations don't actually open the sound file until the cursor is created, so MovieAudioCursor sounds like the place to get it. Is there a reason to also have it on AudioSound?
AudioSound is returned from loader, so I think it only makes sense. Other 2 having it is implementation detail because Panda3D actually has two levels of abstraction you have to go through.

> Would it be interesting to give thought to standardizing the keys between different formats, so that you can use the same code to access the title of an .mp3 file as for an .ogg file, via a named enum or named getters, or do you think the original keys should be kept?
I could implement a series of getters like `getAuthor()`, `getTitle()`, etc. but this seems overkill having on AudioSound and putting them into a separate class isn't much better I think.

2025-11-08 21:45 UTC, Wizzerinus commented
Wanted to ask if the maintainers of the engine were still interested in this 🥺 everything here is complete but (since nothing was done in here) I wanted to wait until flac stuff was merged but it seems cancelled so.

2025-11-09 10:38 UTC, rdb requested changes
Yes I am, sorry for not getting to this sooner. I just have some nits to pick and then we can merge this as far as I'm concerned.

2025-11-09 10:38 UTC, rdb commented on panda/src/audio/audioSound.cxx
> +  for (std::string st : get_raw_comment()) {
No need to make a copy here, so `const std::string &st : get_raw_comment()`

2025-11-09 10:38 UTC, rdb commented on panda/src/audio/audioSound.cxx
> +has_comment(std::string key) const {
No need to copy the key, so `const std::string &key`

2025-11-09 10:38 UTC, rdb commented on panda/src/audio/audioSound.cxx
> +  for (std::string st : get_raw_comment()) {
Same as above

2025-11-09 10:38 UTC, rdb commented on panda/src/audio/audioSound.h
> +  virtual std::vector<std::string> get_raw_comment() const;
Put this further up, don't put this in the middle of the standard type boilerplate

2025-11-09 10:38 UTC, rdb commented on panda/src/audiotraits/openalAudioManager.h
> +    std::vector<std::string> _comment;
This is on the AudioManager, why exactly? Was this a mistake?

2025-11-09 10:38 UTC, rdb commented on panda/src/audiotraits/openalAudioSound.cxx
> +
Add docstring before this method

2025-11-09 10:38 UTC, rdb commented on panda/src/ffmpeg/ffmpegAudioCursor.cxx
> +std::vector<std::string> FfmpegAudioCursor::
Needs docstring

2025-11-09 10:38 UTC, rdb commented on panda/src/ffmpeg/ffmpegAudioCursor.cxx
> +  std::vector<std::string> commentStrings;
Coding style nit: `comment_strings`

2025-11-09 10:38 UTC, rdb commented on panda/src/ffmpeg/ffmpegAudioCursor.cxx
> +  AVDictionaryEntry *tag = NULL;
`nullptr`

2025-11-09 10:38 UTC, rdb commented on panda/src/movies/movieAudioCursor.cxx
> +    return {};
indentation, missing docstring

2025-11-09 10:38 UTC, rdb commented on panda/src/movies/opusAudioCursor.cxx
> +  const OpusTags* tag = op_tags(_op, -1);
nit: `const OpusTags *tag` (it may seem counterintuitive at first that this goes around the identifier, but this matches how C++ parses it)

2025-11-09 10:38 UTC, rdb commented on panda/src/movies/opusAudioCursor.cxx
> +std::vector<std::string> OpusAudioCursor::
We tend to put a docstring everywhere even if it's an empty one
```cpp
/**
 *
 */
```

2025-11-09 10:38 UTC, rdb commented on panda/src/audio/audioSound.cxx
> +std::vector<std::string> AudioSound::
Let's use the `vector_string` class everywhere, this is an alias defined in `vector_string.h` and uses Panda allocators

2025-11-09 19:10 UTC, Wizzerinus commented on panda/src/audio/audioSound.cxx
> +has_comment(std::string key) const {
Yep, I think I wrote that before I knew C++ at a decent level, will fix rq

2025-11-09 19:34 UTC, Wizzerinus commented on panda/src/audiotraits/openalAudioManager.h
> +    std::vector<std::string> _comment;
This is on the SoundData, not AudioManager itself. This is necessary as the stream-parsing method returns instances of SoundData; moving the vector is necessary since SoundData is promptly consumed when OpenALAudioSound is constructed.

2025-11-09 19:55 UTC, Wizzerinus commented on panda/src/audio/audioSound.cxx
> +std::vector<std::string> AudioSound::
After adjusting to this I am getting the following warning on build. I am unsure on the internals of vector_string, so wanted to ask if this was expected:
```
panda/src/audio/audioSound.cxx: In member function ‘virtual vector_string AudioSound::get_raw_comment() const’:
panda/src/audio/audioSound.cxx:206:11: warning: converting to ‘vector_string’ {aka ‘pvector<std::__cxx11::basic_string<char> >’} from initializer list would use explicit constructor ‘pvector<Type>::pvector(TypeHandle) [with Type = std::__cxx11::basic_string<char>]’
  206 |   return {};
```
Everything else builds fine.

2025-11-09 20:13 UTC, rdb commented on panda/src/audio/audioSound.cxx
> +std::vector<std::string> AudioSound::
No, as you can see the build is failing. Just do `return vector_string();` as the constructor is marked explicit

2025-11-09 20:25 UTC, Wizzerinus commented on panda/src/audio/audioSound.cxx
> +std::vector<std::string> AudioSound::
Fixed. Thank you for the assistance 😊 *(no I am not an ai network if it reads like that)*

2025-11-10 09:32 UTC, rdb commented on panda/src/audiotraits/openalAudioManager.h
> +    std::vector<std::string> _comment;
Ah, gotcha

2025-11-10 09:36 UTC, rdb requested changes
Almost there! :)

A unit test might be a nice extra to have as well, if you find time for that

2025-11-10 09:36 UTC, rdb commented on panda/src/audio/audioSound.cxx
> +has_comment(std::string &key) const {
This should be `const std::string &`, requiring a mutable reference is silly and probably wouldn't be wrapped by interrogate.

2025-11-10 09:36 UTC, rdb commented on panda/src/ffmpeg/ffmpegAudioCursor.cxx
> +    comment_strings.push_back(comment);
`std::move(comment)` more efficient here

2025-11-10 09:36 UTC, rdb commented on panda/src/movies/opusAudioCursor.cxx
> +    comments.push_back(tag);
either `std::move(tag)` or `comments.push_back(std::string(...))` so it's already an rvalue

2025-11-10 09:36 UTC, rdb commented on panda/src/movies/vorbisAudioCursor.cxx
> +    comments.push_back(tag);
`std::move(tag)`

2025-11-10 09:36 UTC, rdb commented on panda/src/movies/vorbisAudioCursor.cxx
> +parse_vorbis_comments(vorbis_comment *com) {
Also needs a docstring :)

2025-11-10 12:32 UTC, Wizzerinus commented
should be done

2025-11-10 15:44 UTC, Wizzerinus commented
CI has passed now 🥺

2025-12-18 15:08 UTC, Wizzerinus commented
🥺 I don't mind this being not reviewed since I use custom builds anyway but still

2025-12-29 16:24 UTC, Wizzerinus commented
Rebased and added a way to read comments from FLAC. Note that bundled drflac had to be modified, which may be not ideal (see also my comment on Discord about this).

2026-01-15 09:09 UTC, Wizzerinus commented
I feel like this is difficult to avoid. We cannot return a reference to a vector, because in many cases, there's no vector to take a reference to (i.e. userdata sound, NULL manager, etc). Plus, I feel, most sound tracks don't have huge numbers of comments for this to become a performance bottleneck (especially since this API is not likely to be used every frame, or worse, many times every frame).

I should recheck the code flow again, but sound data should only be fetched from the cursors once if they're loaded by OpenAL, and saved into the AudioSound (this is necessary because cursors are thrown away afterwards), so the FFMPEG call should only be happening once per loaded sound.

2026-01-15 09:18 UTC, rdb commented
You're right, I was conflating get_raw_comment on AudioSound with the one on MovieAudioCursor.

So then all we need to do to make this efficient (no copy every time) is to change the return type on AudioSound to `const vector_string &`

In the base class implementation you can return a reference to a static like so:
```cpp
  static const vector_string empty;
  return empty;
```

2026-01-15 09:48 UTC, Wizzerinus commented
Would this cause lifetime issues if we call getComment() in Python, then have the sound garbage collected? Or does igate convert things into Python lists anyway?

2026-01-15 09:53 UTC, rdb commented
Igate immediately converts it because it doesn't wrap vector_string.

2026-01-15 17:12 UTC, Wizzerinus commented
Adjusted this morning, tests seem to pass

2026-01-16 20:15 UTC, rdb approved these changes
Thanks!

2026-01-16 20:16 UTC, merged